### ISSUE TITLE
Development process content feels in need of a refresh

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-team-manual#211]
https://team-manual.cloud.service.gov.uk/team/working_practices/ starts by showing our Development Process, but it's hard to make changes to this content and it isn't very in-line with the Doing--Reviewing--Approving model that Rubbernecker/PivotalTracker create.

**Comment by 46bit** [comment]
Thanks @bleach! The diagrams and description are quite effective from an IA point of view, but I've found less so from other contexts (e.g., a new team member trying to understand what they should do.)

I'm moving off of the PaaS tomorrow 😢 and these issues are something of a dump of ideas in my head.

**Comment by alext** [comment]
@46bit Do you think #230 has addressed these comments, or does it still need further updating?

**Comment by 46bit** [comment]
We've addressed this well.
