### ISSUE TITLE
Reviewers should be OK to accept things

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-team-manual#212]
On the 24th of April, we decided at Retro that reviewers should be OK to accept stories as well if the story is clearly done. This should be recorded as guidance in the Team Manual, but it's hard to fit in the content in because of #211.

**Comment by bleach** [comment]
Worth checking if the Information Assurance documentation needs updating too. I can't recall if there's anything in there that specifically says that acceptance is done by a different person to review.

**Comment by alext** [comment]
I think the updates in #230 cover this. Closing.
